
import { Language, TranslationSet, PilgrimProfile } from './types';

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  [Language.AR]: {
    title: "رعاية النسك - NuskCare",
    personalData: "البيانات الشخصية",
    medicalHistory: "التاريخ الطبي",
    medications: "التاريخ الدوائي",
    vitalSigns: "القياسات الحيوية",
    emergencyContact: "رقم هاتف الطوارئ",
    callEmergency: "اتصال بالمرافق",
    shareLocation: "مشاركة الموقع",
    enterSecurityCode: "أدخل رمز الأمان",
    securityPrompt: "الرجاء إدخال رمز الأمان الموجود على السوار",
    accessGranted: "تم السماح بالدخول",
    chronicDiseases: "الأمراض المزمنة",
    allergies: "الحساسية",
    surgeries: "العمليات الجراحية",
    bloodType: "فصيلة الدم",
    bloodPressure: "ضغط الدم",
    bloodSugar: "مستوى السكر",
    verify: "تحقق",
    back: "رجوع",
    language: "اللغة",
    editProfile: "تعديل البيانات",
    shareProfile: "مشاركة الملف",
    scanInstructions: "امسح الكود للوصول السريع للملف الطبي الخاص بك",
    close: "إغلاق"
  },
  [Language.EN]: {
    title: "NuskCare Platform",
    personalData: "Demographics",
    medicalHistory: "Medical History",
    medications: "Medication History",
    vitalSigns: "Vital Signs",
    emergencyContact: "Emergency Contact",
    callEmergency: "Call Escort",
    shareLocation: "Share Location",
    enterSecurityCode: "Enter Security Code",
    securityPrompt: "Code on back of bracelet (Default: 1234)",
    accessGranted: "Access Granted",
    chronicDiseases: "Chronic Diseases",
    allergies: "Allergies",
    surgeries: "Surgeries",
    bloodType: "Blood Type",
    bloodPressure: "Blood Pressure",
    bloodSugar: "Blood Sugar",
    verify: "Verify",
    back: "Back",
    language: "Language",
    editProfile: "Edit Profile",
    shareProfile: "Share Profile",
    scanInstructions: "Scan this code for quick access to your medical records",
    close: "Close"
  },
  [Language.UR]: {
    title: "نوسک کیئر پلیٹ فارم",
    personalData: "ذاتی معلومات",
    medicalHistory: "طبی تاریخ",
    medications: "ادویات کی تفصیل",
    vitalSigns: "وائٹل سائنز",
    emergencyContact: "ہنگامی نمبر",
    callEmergency: "ساتھی کو کال کریں",
    shareLocation: "لوکیشن شیئر کریں",
    enterSecurityCode: "سیکیورٹی کوڈ درج کریں",
    securityPrompt: "بریسلٹ کے پیچھے والا کوڈ (ڈیفالٹ: 1234)",
    accessGranted: "رسائی مل گئی",
    chronicDiseases: "دائمی بیماریاں",
    allergies: "الرجی",
    surgeries: "سرجری",
    bloodType: "خون کا گروپ",
    bloodPressure: "بلڈ پریشر",
    bloodSugar: "بلڈ شوگر",
    verify: "تصدیق کریں",
    back: "واپس",
    language: "زبان",
    editProfile: "پروفائل ایڈٹ کریں",
    shareProfile: "پروفائل شیئر کریں",
    scanInstructions: "طبی ریکارڈ تک فوری رسائی کے لیے اس کوڈ کو اسکین کریں",
    close: "بند کریں"
  },
  [Language.ID]: {
    title: "Platform NuskCare",
    personalData: "Data Pribadi",
    medicalHistory: "Riwayat Medis",
    medications: "Riwayat Obat",
    vitalSigns: "Tanda Vital",
    emergencyContact: "Kontak Darurat",
    callEmergency: "Hubungi Pendamping",
    shareLocation: "Bagikan Lokasi",
    enterSecurityCode: "Masukkan Kode Keamanan",
    securityPrompt: "Kode di belakang gelang (Default: 1234)",
    accessGranted: "Akses Diberikan",
    chronicDiseases: "Penyakit Kronis",
    allergies: "Alergi",
    surgeries: "Operasi",
    bloodType: "Golongan Darah",
    bloodPressure: "Tekanan Darah",
    bloodSugar: "Gula Darah",
    verify: "Verifikasi",
    back: "Kembali",
    language: "Bahasa",
    editProfile: "Edit Profil",
    shareProfile: "Bagikan Profil",
    scanInstructions: "Scan kode ini untuk akses cepat ke rekam medis",
    close: "Tutup"
  }
};

export const DEFAULT_PROFILE: PilgrimProfile = {
  id: "H-2024-" + Math.floor(1000 + Math.random() * 9000),
  fullName: "أحمد بن عبدالله",
  nationality: "سعودي",
  nativeLanguage: "العربية",
  passportId: "123456789",
  emergencyContactName: "رئيس الحملة",
  emergencyPhone: "0500000000",
  securityCode: "1234",
  medicalHistory: {
    chronicDiseases: ["السكري"],
    allergies: ["البنسلين"],
    previousSurgeries: []
  },
  medicationHistory: [
    { name: "منظم سكر", dosage: "500ملجم", frequency: "مرتين يومياً" }
  ],
  vitalSigns: {
    bloodSugar: "140 mg/dL",
    bloodPressure: "120/80 mmHg",
    bloodType: "O+",
    lastUpdated: new Date().toLocaleString()
  }
};
